sudo: required
services:
    - docker

before_install:
    - docker build -t longmaster/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run longmaster/react-test npm test -- --coverage

after_success:
    - docker build -t longmaster/multi-client ./client
    - docker build -t longmaster/multi-nginx ./nginx
    - docker build -t longmaster/multi-server ./server
    - docker build -t longmaster/multi-worker ./worker
    #Login to the docker CLI
    - echo $DOCKER_ID 
    - docker login -u="$DOCKER_ID" -p="$DOCKER_PASSWORD"
    #Take those images and push them to docker hub
    - docker push longmaster/multi-client
    - docker push longmaster/multi-nginx
    - docker push longmaster/multi-server
    - docker push longmaster/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-927774926989
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY